# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Проекты\Python\Arduino\Arduino.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 700)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1500, 850))
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("/* === Shared === */\n"
"QStackedWidget, QLabel, QPushButton, QRadioButton, QCheckBox, \n"
"QGroupBox, QStatusBar, QToolButton, QComboBox, QDialog {\n"
"    color: #185f9e;\n"
"}\n"
"/* === QWidget === */\n"
"QWidget:window {\n"
"    background: #FBFFFE;\n"
"    color: #185f9e;\n"
"}\n"
"\n"
"/* === WebView === */\n"
"QTextBrowser, QWebView {\n"
"    background-color: #e9f2f0;\n"
"    selection-color: #6dd69e; \n"
"    selection-background-color: #8f9ff7;\n"
"}\n"
"\n"
"/* === QPushButton === */\n"
"QPushButton {\n"
"    background-color: #CEFDF2;\n"
"    border: 0.5px solid #a9bdc9;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #daf2e7;\n"
"    border-color: #a9bdc9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88b8b4;\n"
"    border-color: #a9bdc9;\n"
"    color: #e6fff5;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #e6fff5;\n"
"}\n"
"\n"
"\n"
"/* === QComboBox === */\n"
"QComboBox {\n"
"    background-color: #CEFDF2;\n"
"    border: 0.5 px solid #a9bdc9;\n"
"    color: #185f9e;\n"
"    padding: 1px 2px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background: #88b8b4;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-left: 1px solid #a9bdc9;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    border: 2px solid #a9bdc9;\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"/* === QTabBar === */\n"
"QTabBar::tab {\n"
"    background: #EDFDFF;\n"
"    border: 0.5px solid #a9bdc9;\n"
"    border-bottom: none;\n"
"    color: #185f9e;\n"
"    padding-left: 5px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"}\n"
"QTabWidget::pane {\n"
"    background: #F5FFFD;\n"
"    border: 1px solid #a9bdc9;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-bottom: none;\n"
"    background-color: #daf2e7;\n"
"    border-color: #a9bdc9;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 0.5px solid #a9bdc9;\n"
"    background-color: #cef2f2;\n"
"    border-color: #a9bdc9;\n"
"    color: #185f9e;\n"
"}\n"
"\n"
"\n"
"/* === QToolBar === */\n"
"QToolBar {\n"
"    background-color: #a9bdc9;\n"
"    border: none;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"\n"
"\n"
"QToolBar::separator {\n"
"    width: 6px;\n"
"    background-color: #a9bdc9;\n"
"}\n"
"\n"
"/* === QToolButton === */\n"
"QToolButton {\n"
"    border: 1px solid #a9bdc9;\n"
"    margin: 1px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #a9bdc9;\n"
"    border: 1px solid #ebf2da;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] { /* only for MenuButtonPopup */\n"
"    padding-right: 20px; /* make way for the popup button */\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"    border-left: 1px solid #a9bdc9;\n"
"    background: transparent;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QToolButton::menu-button:hover {\n"
"    border-left: 1px solid #ebf2da;\n"
"    background: transparent;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"    background-color: #ccdbba;\n"
"    color: white;\n"
"}\n"
"\n"
"/* === QMenu === */\n"
"QMenu {\n"
"    background-color: #e9f2f0;\n"
"    border: 1px solid light gray;\n"
"    color: white;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 2px 25px 2px 20px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QMenu::item:disabled {\n"
"    color: #b3c8c9;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    border-color: light gray;\n"
"    background: #a9bdc9;\n"
"}\n"
"\n"
"QMenu::icon:checked {\n"
"\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #a9bdc9;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    margin-top: 1px;\n"
"    margin-bottom: 1px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"/* === QMenuBar === */\n"
"QMenuBar {\n"
"    background-color: #e9f2f0;\n"
"    color: #185f9e;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: #e9f2f0;\n"
"}\n"
"\n"
"QMenuBar::item:disabled {\n"
"    color: light gray;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #a9bdc9;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background: #ebf2da;\n"
"}\n"
" \n"
"/* === QScrollBar:vertical === */\n"
"QScrollBar:vertical {\n"
"    background: #e9f2f0;\n"
"    width: 16px;\n"
"    margin: 16px 0 16px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #a9bdc9;\n"
"    min-height: 16px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: #ebf2da;\n"
"    height: 16px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #ebf2da;\n"
"    height: 16px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:up-arrow:vertical, QScrollBar:down-arrow:vertical {\n"
"    border: 2px solid #a9bdc9;\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: #e6e6e6;\n"
"}\n"
"\n"
"/* === QScrollBar:horizontal === */\n"
"QScrollBar:horizontal {\n"
"    background: #e9f2f0;\n"
"    height: 16px;\n"
"    margin: 0 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #a9bdc9;\n"
"    min-width: 16px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: #ebf2da;\n"
"    width: 16px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: #ebf2da;\n"
"    width: 16px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:left-arrow:horizontal, QScrollBar:right-arrow:horizontal {\n"
"    border: 2px solid #a9bdc9;\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: #e6e6e6;\n"
"}\n"
"\n"
"/* =================== */\n"
"QLineEdit, QListView, QTreeView, QTableView, QAbstractSpinBox {\n"
"    background-color: #CEFDF2;\n"
"    color: #185f9e;\n"
"    border: 1px solid #a9bdc9;\n"
"}\n"
"\n"
"QAbstractScrollArea, QLineEdit, QTextEdit, QAbstractSpinBox, QComboBox {\n"
"    border-color: #a9bdc9;\n"
"    border: 1px solid #a9bdc9;\n"
"\n"
"}\n"
"\n"
"/* === QHeaderView === */\n"
"QHeaderView {\n"
"    background: #a9bdc9;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #a9bdc9;\n"
"    border: 0;\n"
"    color: #e9fffc;\n"
"    padding: 3px 0 3px 4px;\n"
"}\n"
"\n"
"/* === Customizations === */\n"
"QFrame#infoLabel {\n"
"    border: 1px inset #a9bdc9;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(150, 200))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setContentsMargins(17, 17, 17, 17)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 180))
        self.label.setMaximumSize(QtCore.QSize(16777215, 230))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 2, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_5.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hallCount = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hallCount.sizePolicy().hasHeightForWidth())
        self.hallCount.setSizePolicy(sizePolicy)
        self.hallCount.setMinimumSize(QtCore.QSize(182, 40))
        self.hallCount.setMaximumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hallCount.setFont(font)
        self.hallCount.setMinimum(2)
        self.hallCount.setMaximum(999)
        self.hallCount.setProperty("value", 4)
        self.hallCount.setObjectName("hallCount")
        self.gridLayout_4.addWidget(self.hallCount, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 2, 2, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_6.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.IDboard = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDboard.sizePolicy().hasHeightForWidth())
        self.IDboard.setSizePolicy(sizePolicy)
        self.IDboard.setMinimumSize(QtCore.QSize(182, 40))
        self.IDboard.setMaximumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.IDboard.setFont(font)
        self.IDboard.setObjectName("IDboard")
        self.gridLayout_9.addWidget(self.IDboard, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_6, 0, 3, 2, 1)
        self.gridLayout_7.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1100, 450))
        self.frame.setMaximumSize(QtCore.QSize(1300, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 220))
        self.groupBox.setMaximumSize(QtCore.QSize(650, 300))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setObjectName("gridLayout")
        self.portArduino = QtWidgets.QComboBox(self.groupBox)
        self.portArduino.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portArduino.sizePolicy().hasHeightForWidth())
        self.portArduino.setSizePolicy(sizePolicy)
        self.portArduino.setMinimumSize(QtCore.QSize(230, 40))
        self.portArduino.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.portArduino.setFont(font)
        self.portArduino.setEditable(False)
        self.portArduino.setObjectName("portArduino")
        self.gridLayout.addWidget(self.portArduino, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(235, 40))
        self.label_4.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(235, 40))
        self.label_6.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.typeConnectArduino = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeConnectArduino.sizePolicy().hasHeightForWidth())
        self.typeConnectArduino.setSizePolicy(sizePolicy)
        self.typeConnectArduino.setMinimumSize(QtCore.QSize(230, 40))
        self.typeConnectArduino.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.typeConnectArduino.setFont(font)
        self.typeConnectArduino.setObjectName("typeConnectArduino")
        self.typeConnectArduino.addItem("")
        self.typeConnectArduino.addItem("")
        self.gridLayout.addWidget(self.typeConnectArduino, 1, 1, 1, 1)
        self.connectArduino = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectArduino.sizePolicy().hasHeightForWidth())
        self.connectArduino.setSizePolicy(sizePolicy)
        self.connectArduino.setMinimumSize(QtCore.QSize(230, 40))
        self.connectArduino.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.connectArduino.setFont(font)
        self.connectArduino.setObjectName("connectArduino")
        self.gridLayout.addWidget(self.connectArduino, 6, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 220))
        self.groupBox_2.setMaximumSize(QtCore.QSize(650, 300))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(235, 40))
        self.label_5.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.connectSupply = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectSupply.sizePolicy().hasHeightForWidth())
        self.connectSupply.setSizePolicy(sizePolicy)
        self.connectSupply.setMinimumSize(QtCore.QSize(210, 40))
        self.connectSupply.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.connectSupply.setFont(font)
        self.connectSupply.setStyleSheet("QPushButton {\n"
"    background-color: #CEFDF2;\n"
"    border: 0.5px solid #a9bdc9;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #daf2e7;\n"
"    border-color: #a9bdc9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88b8b4;\n"
"    border-color: #a9bdc9;\n"
"    color: #e6fff5;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: #e6fff5;\n"
"}")
        self.connectSupply.setObjectName("connectSupply")
        self.gridLayout_2.addWidget(self.connectSupply, 3, 1, 1, 1)
        self.portSupply = QtWidgets.QComboBox(self.groupBox_2)
        self.portSupply.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portSupply.sizePolicy().hasHeightForWidth())
        self.portSupply.setSizePolicy(sizePolicy)
        self.portSupply.setMinimumSize(QtCore.QSize(210, 40))
        self.portSupply.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.portSupply.setFont(font)
        self.portSupply.setObjectName("portSupply")
        self.gridLayout_2.addWidget(self.portSupply, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setMinimumSize(QtCore.QSize(235, 40))
        self.label_12.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.typeConnectSupply = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeConnectSupply.sizePolicy().hasHeightForWidth())
        self.typeConnectSupply.setSizePolicy(sizePolicy)
        self.typeConnectSupply.setMinimumSize(QtCore.QSize(210, 40))
        self.typeConnectSupply.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.typeConnectSupply.setFont(font)
        self.typeConnectSupply.setObjectName("typeConnectSupply")
        self.typeConnectSupply.addItem("")
        self.typeConnectSupply.addItem("")
        self.gridLayout_2.addWidget(self.typeConnectSupply, 0, 1, 1, 1)
        self.idnSupply = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idnSupply.sizePolicy().hasHeightForWidth())
        self.idnSupply.setSizePolicy(sizePolicy)
        self.idnSupply.setMinimumSize(QtCore.QSize(210, 40))
        self.idnSupply.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idnSupply.setFont(font)
        self.idnSupply.setObjectName("idnSupply")
        self.gridLayout_2.addWidget(self.idnSupply, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setMinimumSize(QtCore.QSize(235, 40))
        self.label_13.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setMinimumSize(QtCore.QSize(500, 200))
        self.groupBox_3.setMaximumSize(QtCore.QSize(650, 270))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.StartArduino = QtWidgets.QPushButton(self.groupBox_3)
        self.StartArduino.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartArduino.sizePolicy().hasHeightForWidth())
        self.StartArduino.setSizePolicy(sizePolicy)
        self.StartArduino.setMinimumSize(QtCore.QSize(230, 40))
        self.StartArduino.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.StartArduino.setFont(font)
        self.StartArduino.setObjectName("StartArduino")
        self.gridLayout_5.addWidget(self.StartArduino, 2, 1, 1, 1)
        self.LoadArduino = QtWidgets.QPushButton(self.groupBox_3)
        self.LoadArduino.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoadArduino.sizePolicy().hasHeightForWidth())
        self.LoadArduino.setSizePolicy(sizePolicy)
        self.LoadArduino.setMinimumSize(QtCore.QSize(235, 40))
        self.LoadArduino.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LoadArduino.setFont(font)
        self.LoadArduino.setObjectName("LoadArduino")
        self.gridLayout_5.addWidget(self.LoadArduino, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setMinimumSize(QtCore.QSize(235, 40))
        self.label_8.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.motion = QtWidgets.QComboBox(self.groupBox_3)
        self.motion.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motion.sizePolicy().hasHeightForWidth())
        self.motion.setSizePolicy(sizePolicy)
        self.motion.setMinimumSize(QtCore.QSize(230, 40))
        self.motion.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.motion.setFont(font)
        self.motion.setObjectName("motion")
        self.motion.addItem("")
        self.motion.addItem("")
        self.motion.addItem("")
        self.gridLayout_5.addWidget(self.motion, 0, 1, 1, 1)
        self.startSide = QtWidgets.QCheckBox(self.groupBox_3)
        self.startSide.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startSide.sizePolicy().hasHeightForWidth())
        self.startSide.setSizePolicy(sizePolicy)
        self.startSide.setMinimumSize(QtCore.QSize(0, 40))
        self.startSide.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startSide.setFont(font)
        self.startSide.setStyleSheet("/*-----QCheckBox-----*/\n"
"\n"
"\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 300px;\n"
"    height: 50px;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"   image:url(:/Forward/Forward.png) ;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    image:url(:/Forward/Forward.png) ;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    image:url(:/Forward/Forward.png) ;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image:url(:/Back/Back.png) ;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    image:url(:/Back/Back.png) ;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    image:url(:/Back/Back.png) ;\n"
"}\n"
"\n"
"")
        self.startSide.setText("")
        self.startSide.setTristate(False)
        self.startSide.setObjectName("startSide")
        self.gridLayout_5.addWidget(self.startSide, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(235, 40))
        self.label_7.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setMinimumSize(QtCore.QSize(500, 200))
        self.groupBox_4.setMaximumSize(QtCore.QSize(650, 270))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.CCSupply = QtWidgets.QPushButton(self.groupBox_4)
        self.CCSupply.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CCSupply.sizePolicy().hasHeightForWidth())
        self.CCSupply.setSizePolicy(sizePolicy)
        self.CCSupply.setMinimumSize(QtCore.QSize(430, 40))
        self.CCSupply.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CCSupply.setFont(font)
        self.CCSupply.setObjectName("CCSupply")
        self.gridLayout_6.addWidget(self.CCSupply, 0, 0, 1, 2)
        self.current = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.current.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current.sizePolicy().hasHeightForWidth())
        self.current.setSizePolicy(sizePolicy)
        self.current.setMinimumSize(QtCore.QSize(235, 40))
        self.current.setMaximumSize(QtCore.QSize(240, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.current.setFont(font)
        self.current.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.current.setObjectName("current")
        self.gridLayout_6.addWidget(self.current, 1, 0, 1, 1)
        self.setCurrent = QtWidgets.QPushButton(self.groupBox_4)
        self.setCurrent.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setCurrent.sizePolicy().hasHeightForWidth())
        self.setCurrent.setSizePolicy(sizePolicy)
        self.setCurrent.setMinimumSize(QtCore.QSize(240, 40))
        self.setCurrent.setMaximumSize(QtCore.QSize(340, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setCurrent.setFont(font)
        self.setCurrent.setObjectName("setCurrent")
        self.gridLayout_6.addWidget(self.setCurrent, 1, 1, 1, 1)
        self.offCurrent = QtWidgets.QPushButton(self.groupBox_4)
        self.offCurrent.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offCurrent.sizePolicy().hasHeightForWidth())
        self.offCurrent.setSizePolicy(sizePolicy)
        self.offCurrent.setMinimumSize(QtCore.QSize(430, 40))
        self.offCurrent.setMaximumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.offCurrent.setFont(font)
        self.offCurrent.setObjectName("offCurrent")
        self.gridLayout_6.addWidget(self.offCurrent, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Система управления движением \n"
"магнитолевитационного транспорта \n"
"с рекуперацией энергии\n"
"на основе Arduino Mega и Python 3.12"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Число датчиков"))
        self.groupBox_6.setTitle(_translate("MainWindow", "ID платы"))
        self.groupBox.setTitle(_translate("MainWindow", "Подключение комплекса"))
        self.label_4.setText(_translate("MainWindow", "Подключение"))
        self.label_6.setText(_translate("MainWindow", "Порт прибора"))
        self.typeConnectArduino.setItemText(0, _translate("MainWindow", "Автоматически"))
        self.typeConnectArduino.setItemText(1, _translate("MainWindow", "Вручную"))
        self.connectArduino.setText(_translate("MainWindow", "Подключить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Подключение источника тока"))
        self.label_5.setText(_translate("MainWindow", "Идентификатор"))
        self.connectSupply.setText(_translate("MainWindow", "Подключить"))
        self.label_12.setText(_translate("MainWindow", "Порт прибора"))
        self.typeConnectSupply.setItemText(0, _translate("MainWindow", "Автоматически"))
        self.typeConnectSupply.setItemText(1, _translate("MainWindow", "Вручную"))
        self.label_13.setText(_translate("MainWindow", "Подключение"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Выбор режима работы"))
        self.StartArduino.setText(_translate("MainWindow", "Запустить"))
        self.LoadArduino.setText(_translate("MainWindow", "Загрузить код"))
        self.label_8.setText(_translate("MainWindow", "Направление"))
        self.motion.setItemText(0, _translate("MainWindow", "Разгон"))
        self.motion.setItemText(1, _translate("MainWindow", "Поддержание скорости"))
        self.motion.setItemText(2, _translate("MainWindow", "Торможение"))
        self.label_7.setText(_translate("MainWindow", "Режим движения"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Управление током"))
        self.CCSupply.setText(_translate("MainWindow", "Режим стабилизации тока"))
        self.setCurrent.setText(_translate("MainWindow", "Установить ток"))
        self.offCurrent.setText(_translate("MainWindow", "Отключить ток"))
# import Slider_rc
